apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-self-sync
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/absolute-Idee/GitOps.git
    targetRevision: main
    path: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: false