apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-stand
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/absolute-Idee/GitOps.git
    targetRevision: main
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true